# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.18.5
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.0.4-fabric-26.1
maven_group=identitytheft.raildestinations
archives_base_name=rail-destinations

# Dependencies
fabric_api_version=0.144.3+26.1